apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-lsst-lsp-localhost-dax-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: project-lsst-lsp-localhost-dax
