apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasets-lsst-lsp-localhost-dax-claim
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 400Mi
  volumeName: datasets-lsst-lsp-localhost-dax
